// Code generated by Kitex v0.9.1. DO NOT EDIT.

package fileuploadservice

import (
	server "github.com/cloudwego/kitex/server"
	clientTransform "github.com/pk5ls20/NekoImageWorkflow/kitex_gen/proto/clientTransform"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler clientTransform.FileUploadService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
