// Code generated by Kitex v0.9.1. DO NOT EDIT.
package fileuploadservice

import (
	server "github.com/cloudwego/kitex/server"
	clientTransform "github.com/pk5ls20/NekoImageWorkflow/kitex_gen/proto/clientTransform"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler clientTransform.FileUploadService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler clientTransform.FileUploadService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
