name: Run all test
on:
  push:
  workflow_dispatch:
jobs:
  basis-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.21.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1
      - name: Run go vet on uploadClient
        run: cd uploadClient && go vet ./...
      - name: Run go test on uploadClient
        run: cd uploadClient && go test -v -race -coverprofile=coverage1.out -covermode=atomic ./...
      - name: Upload uploadClient module coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./uploadClient/coverage1.out
          flags: uploadClient
      - name: Run go vet on common
        run: cd common && go vet ./...
      - name: Run go test on common
        run: cd common && go test -v -race -coverprofile=coverage2.out -covermode=atomic ./...
      - name: Upload common module coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./common/coverage2.out
          flags: common