name: Run all test
on:
  push:
  workflow_dispatch:
jobs:
  basis-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.21.1
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.1
      - name: Run go test on uploadClient
        run: cd uploadClient && go test -v -race -coverprofile=coverage.out -covermode=atomic ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./uploadClient/coverage.out
          flags: uploadClient